import { useEffect, useState } from 'react'
import './App.css'
import { api, getApiUrl, setApiUrl } from './services/api'
import type { Analysis, BotState, Dashboard, FeedItem, Group, HistoryItem, Notification, Opportunity, Page, Post, Scheduler } from './types'

const nav: { label: Page; icon: string }[] = [{ label: 'Dashboard', icon: '⌂' }, { label: 'Groups', icon: '◈' }, { label: 'Feed', icon: '≡' }, { label: 'Posts', icon: '□' }, { label: 'Scheduler', icon: '◷' }, { label: 'Notifications', icon: '♢' }, { label: 'Opportunities', icon: '↗' }, { label: 'Settings', icon: '⚙' }]
const seedGroups: Group[] = Array.from({ length: 12 }, (_, index) => ({ id: `group_${index + 1}`, name: ['Blockchain Founders', 'Web3 Developers', 'Startup Operators', 'Remote Builders', 'Gaming Founders'][index % 5], username: `community_${index + 1}`, description: 'A focused community for practical collaboration, shared learning, and new opportunities.', member_count: 18420 - index * 613, category: ['Blockchain', 'Developers', 'Startups', 'Remote Jobs'][index % 4], keywords: ['startup', 'builders'], joined: false }))
const seedPosts: Post[] = [{ id: 'post_1', title: 'Strategic partnership', post_type: 'Partnership', content: 'We are looking for thoughtful strategic partners to build the next chapter together.', enabled: true, usage_count: 12, created_at: '2026-09-20' }, { id: 'post_2', title: 'Product builders wanted', post_type: 'Job', content: 'Seeking experienced builders interested in a focused, remote collaboration.', enabled: true, usage_count: 7, created_at: '2026-09-18' }]
const seedDashboard: Dashboard = { groups: 42, active_feed: 4, total_posts: 8, posts_today: 3, skipped_posts: 2, replies: 5, unread_notifications: 3, investors: 12, partners: 19 }

function App() {
  const [page, setPage] = useState<Page>('Dashboard')
  const [groups, setGroups] = useState<Group[]>(seedGroups)
  const [posts, setPosts] = useState<Post[]>(seedPosts)
  const [feed, setFeed] = useState<FeedItem[]>([])
  const [history, setHistory] = useState<HistoryItem[]>([])
  const [notifications, setNotifications] = useState<Notification[]>([])
  const [opportunities, setOpportunities] = useState<Opportunity[]>([])
  const [dashboard, setDashboard] = useState(seedDashboard)
  const [botState, setBotState] = useState<BotState>('STOPPED')
  const [search, setSearch] = useState('')
  const [selectedGroup, setSelectedGroup] = useState<Group | null>(null)
  const [analysis, setAnalysis] = useState<Analysis | null>(null)
  const [connected, setConnected] = useState(false)
  const [serverUrl, setServerUrl] = useState(getApiUrl())
  const [scheduler, setScheduler] = useState<Scheduler>({ auto_mode: true, start_time: '09:00', end_time: '20:00', working_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], posting_interval: 30, minimum_messages: 20, maximum_posts_per_day: 25, timezone: 'UTC' })

  useEffect(() => { void api.health().then(() => setConnected(true)).catch(() => setConnected(false)) }, [])
  useEffect(() => { void api.notifications().then(setNotifications).catch(() => setNotifications([])) }, [])
  const doSearch = async (value: string) => { setSearch(value); try { setGroups(await api.groups(value)) } catch { setGroups(seedGroups.filter((group) => `${group.name} ${group.description} ${group.category}`.toLowerCase().includes(value.toLowerCase()))) } }
  const toggleBot = async () => { const next = botState === 'RUNNING' ? 'stop' : 'start'; try { const result = await api.bot(next); setBotState(result.state as BotState); setHistory(await api.history()); setDashboard(await api.dashboard()) } catch { setBotState(next === 'start' ? 'RUNNING' : 'STOPPED') } }
  const addGroup = async (group: Group) => { try { const item = await api.addFeed(group.id); setFeed((current) => [...current, item]) } catch { setFeed((current) => current.some((item) => item.group.id === group.id) ? current : [...current, { id: group.id, group, position: current.length, enabled: true, selected_post_id: posts[0]?.id ?? null, last_posted: null, post_count: 0, next_scheduled_time: 'Ready' }]) } }
  const openGroup = async (group: Group) => { setSelectedGroup(group); setPage('Groups'); try { setAnalysis(await api.analyze(group.id)) } catch { setAnalysis({ activities: ['Startup discussions', 'Business networking', 'Knowledge sharing'], member_types: ['Founders', 'Developers', 'Investors'], partnership: { status: 'suitable', reason: 'The group focus supports relevant collaboration. This is an AI-assisted recommendation.', confidence: 0.84 }, job: { status: 'possibly_suitable', reason: 'Job-related content may fit when directly relevant.', confidence: 0.71 }, posting_style: ['Specific and concise', 'Value-led', 'Low frequency'], risks: ['Avoid repetitive messages', 'Avoid aggressive sales language'] }) } }
  const renderContent = () => {
    if (page === 'Groups') return <GroupsPage groups={groups} search={search} onSearch={doSearch} onOpen={openGroup} onAdd={addGroup} selectedGroup={selectedGroup} analysis={analysis} onOpportunities={async () => { if (selectedGroup) { try { setOpportunities(await api.opportunities(selectedGroup.id)) } catch { setOpportunities([{ id: 'op_1', group_id: selectedGroup.id, group_name: selectedGroup.name, username: 'alex', category: 'investment', evidence: 'I invest in early-stage gaming startups.', evidence_level: 'explicit', confidence: 0.86 }]) } setPage('Opportunities') } }} />
    if (page === 'Feed') return <FeedPage feed={feed} posts={posts} onAdd={() => setPage('Groups')} />
    if (page === 'Posts') return <PostsPage posts={posts} onCreate={async (post) => { try { setPosts([...posts, await api.createPost(post)]) } catch { setPosts([...posts, { ...post, id: `post_${posts.length + 1}`, enabled: true, usage_count: 0, created_at: new Date().toISOString() }]) } }} />
    if (page === 'Scheduler') return <SchedulerPage settings={scheduler} onChange={setScheduler} onSave={async () => { try { await api.saveScheduler(scheduler) } catch { /* local demo */ } }} />
    if (page === 'Notifications') return <NotificationsPage notifications={notifications} onRead={async (id) => { try { await api.markNotificationRead(id) } finally { setNotifications((current) => current.map((item) => item.id === id ? { ...item, read: true } : item)) } }} onReadAll={async () => { try { await api.markAllNotificationsRead() } finally { setNotifications((current) => current.map((item) => ({ ...item, read: true }))) } }} />
    if (page === 'Opportunities') return <OpportunitiesPage opportunities={opportunities} />
    if (page === 'Settings') return <SettingsPage url={serverUrl} onSave={(url) => { setServerUrl(url); setApiUrl(url) }} connected={connected} />
    return <DashboardPage dashboard={dashboard} botState={botState} onToggle={toggleBot} history={history} onViewHistory={() => setPage('Feed')} />
  }
  return <div className="shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">T</span><span>Auto Bot</span></div><div className="mode">MOCK MODE <span className="live-dot" /></div><nav>{nav.map((item) => <button className={page === item.label ? 'nav-item active' : 'nav-item'} key={item.label} onClick={() => setPage(item.label)}><span>{item.icon}</span>{item.label}{item.label === 'Notifications' && <b>3</b>}</button>)}</nav><div className="sidebar-foot"><div className="server-state"><span className={connected ? 'status-dot' : 'status-dot offline'} />{connected ? 'Server connected' : 'Demo mode'}</div><small>Independent automation<br />No Telegram integration</small></div></aside><main className="main"><header><div><p className="eyebrow">WORKSPACE / {page.toUpperCase()}</p><h1>{page === 'Dashboard' ? 'Good morning, operator.' : page}</h1></div><div className="header-actions"><span className="data-badge"><span className="status-dot" /> Mock data</span><button className="icon-button" title="Notifications" onClick={() => setPage('Notifications')}>♢<b>3</b></button><div className="avatar">AB</div></div></header><div className="content">{renderContent()}</div></main></div>
}

function DashboardPage({ dashboard, botState, onToggle, history, onViewHistory }: { dashboard: Dashboard; botState: BotState; onToggle: () => void; history: HistoryItem[]; onViewHistory: () => void }) { const metrics = [['Groups', dashboard.groups, '↑ 8.2%', 'blue'], ['Active feed', dashboard.active_feed, '4 ready', 'mint'], ['Posts today', dashboard.posts_today, 'of 25 max', 'amber'], ['Replies', dashboard.replies, '↑ 2 today', 'rose'], ['Investors', dashboard.investors, 'signals', 'violet'], ['Partners', dashboard.partners, 'signals', 'coral']]; return <><section className="hero-panel"><div><p className="kicker">AUTOMATION CONTROL</p><h2>Keep your outreach<br /><em>intentional.</em></h2><p className="hero-copy">Your mock workspace is ready. Groups, posts, and opportunities stay organized while the server handles the rotation.</p><button className={botState === 'RUNNING' ? 'button danger' : 'button primary'} onClick={onToggle}>{botState === 'RUNNING' ? '■ STOP BOT' : '▶ START BOT'}</button></div><div className="bot-orbit"><div className="orbit-ring" /><div className="bot-core"><span>{botState === 'RUNNING' ? '●' : '○'}</span><small>BOT STATUS</small><strong>{botState}</strong></div></div></section><div className="metric-grid">{metrics.map(([label, value, detail, color]) => <div className={`metric ${color}`} key={label}><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>)}</div><div className="split-grid"><section className="panel"><div className="panel-head"><div><p className="kicker">RECENT ACTIVITY</p><h3>Posting history</h3></div><button className="text-button" onClick={onViewHistory}>View all ↗</button></div>{history.length === 0 ? <div className="empty-state"><span>◷</span><p>No posting activity yet.</p><small>Start the bot to simulate the first feed rotation.</small></div> : history.slice(0, 3).map((item) => <div className="activity-row" key={item.id}><span className={`activity-icon ${item.status}`}>{item.status === 'success' ? '✓' : '–'}</span><div><strong>{item.group_name}</strong><small>{item.post_title || 'No post selected'} · {item.reason}</small></div><time>{item.status.toUpperCase()}</time></div>)}</section><section className="panel focus-panel"><p className="kicker">OPPORTUNITY PULSE</p><h3>Signals worth a look</h3><div className="signal"><span className="signal-icon violet">↗</span><div><strong>12 potential investors</strong><small>Across your analyzed groups</small></div><b>86%</b></div><div className="signal"><span className="signal-icon coral">⌁</span><div><strong>19 partner signals</strong><small>Evidence-backed opportunities</small></div><b>81%</b></div><div className="disclaimer">AI findings are suggestions based on available mock messages, not verified facts.</div></section></div></> }

function GroupsPage({ groups, search, onSearch, onOpen, onAdd, selectedGroup, analysis, onOpportunities }: { groups: Group[]; search: string; onSearch: (value: string) => void; onOpen: (group: Group) => void; onAdd: (group: Group) => void; selectedGroup: Group | null; analysis: Analysis | null; onOpportunities: () => void }) { return <div className="groups-layout"><section><div className="search-wrap"><span>⌕</span><input value={search} onChange={(event) => onSearch(event.target.value)} placeholder="Search groups, keywords, categories..." /><kbd>⌘ K</kbd></div><div className="result-head"><span>{groups.length} groups discovered</span><span>Sorted by relevance ↓</span></div>{groups.map((group, index) => <div className="group-row" key={group.id}><div className="group-avatar">{group.name.slice(0, 1)}</div><div className="group-info"><strong>{group.name}</strong><span>@{group.username} · {group.member_count.toLocaleString()} members</span><p>{group.description}</p><div className="chips"><span>{group.category}</span><span>Relevance: {91 - index % 8}%</span></div></div><div className="group-actions"><button className="small-button" onClick={() => onOpen(group)}>Analyze</button><button className="small-button filled" onClick={() => onAdd(group)}>+ Feed</button></div></div>)}</section><aside className="detail-panel">{selectedGroup && analysis ? <><div className="detail-top"><span className="group-avatar large">{selectedGroup.name.slice(0, 1)}</span><div><p className="kicker">GROUP ANALYSIS</p><h3>{selectedGroup.name}</h3><span>@{selectedGroup.username}</span></div></div><div className="analysis-block"><label>PRIMARY ACTIVITIES</label><p>{analysis.activities.join(' · ')}</p></div><div className="analysis-block"><label>LIKELY MEMBER TYPES</label><div className="chips">{analysis.member_types.map((type) => <span key={type}>{type}</span>)}</div></div><div className="suitability"><div><label>PARTNERSHIP</label><strong>{analysis.partnership.status.replace('_', ' ')}</strong><small>{Math.round(analysis.partnership.confidence * 100)}% confidence</small></div><div><label>JOB POSTS</label><strong>{analysis.job.status.replace('_', ' ')}</strong><small>{Math.round(analysis.job.confidence * 100)}% confidence</small></div></div><div className="analysis-block"><label>POSTING RISKS</label>{analysis.risks.map((risk) => <p className="risk" key={risk}>× {risk}</p>)}</div><button className="button primary full" onClick={onOpportunities}>Explore opportunities ↗</button></> : <div className="detail-empty"><span>◈</span><h3>Select a group</h3><p>Analyze a result to inspect activity, suitability, and posting risks.</p></div>}</aside></div> }

function FeedPage({ feed, posts, onAdd }: { feed: FeedItem[]; posts: Post[]; onAdd: () => void }) { return <><div className="page-toolbar"><div><p className="kicker">ORDERED ROTATION</p><h2>Your posting feed</h2></div><button className="button primary" onClick={onAdd}>+ Add group</button></div><section className="panel feed-list">{feed.length === 0 ? <div className="empty-state"><span>≡</span><p>Your feed is empty.</p><small>Add groups from the Groups page to start a controlled rotation.</small></div> : feed.map((item, index) => <div className="feed-row" key={item.id}><b className="feed-number">{String(index + 1).padStart(2, '0')}</b><div className="group-avatar">{item.group.name.slice(0, 1)}</div><div className="feed-info"><strong>{item.group.name}</strong><span>{item.group.member_count.toLocaleString()} members · {item.enabled ? 'Enabled' : 'Disabled'}</span></div><select defaultValue={item.selected_post_id ?? ''}><option value="">Select post</option>{posts.map((post) => <option key={post.id} value={post.id}>{post.title}</option>)}</select><span className="feed-count">{item.post_count} posts</span><button className="icon-button" title="Move item">⋮⋮</button></div>)}</section></> }

function PostsPage({ posts, onCreate }: { posts: Post[]; onCreate: (post: Pick<Post, 'title' | 'post_type' | 'content'>) => void }) { const [draft, setDraft] = useState({ title: '', post_type: 'Partnership' as Post['post_type'], content: '' }); return <><div className="page-toolbar"><div><p className="kicker">CONTENT LIBRARY</p><h2>Posts that sound like you</h2></div></div><div className="posts-layout"><section>{posts.map((post) => <article className="post-card" key={post.id}><div className="post-card-head"><span className="type-label">{post.post_type}</span><span className="toggle on" /><span className="post-status">Active</span></div><h3>{post.title}</h3><p>{post.content}</p><footer><span>Used {post.usage_count} times</span><button className="text-button">Edit</button><button className="text-button">Duplicate</button></footer></article>)}</section><section className="panel editor"><p className="kicker">NEW POST</p><h3>Create a post</h3><label>Title<input value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} placeholder="Looking for strategic partners" /></label><label>Type<select value={draft.post_type} onChange={(event) => setDraft({ ...draft, post_type: event.target.value as Post['post_type'] })}><option>Partnership</option><option>Job</option><option>Investment</option><option>Business</option><option>General</option></select></label><label>Content<textarea value={draft.content} onChange={(event) => setDraft({ ...draft, content: event.target.value })} placeholder="Write a clear, relevant message..." /></label><button className="button primary full" onClick={() => { if (draft.title && draft.content) { onCreate(draft); setDraft({ title: '', post_type: 'Partnership', content: '' }) } }}>Save post</button></section></div></> }

function SchedulerPage({ settings, onChange, onSave }: { settings: Scheduler; onChange: (settings: Scheduler) => void; onSave: () => void }) { const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']; return <div className="settings-layout"><section className="panel form-panel"><p className="kicker">AUTOMATION WINDOW</p><h2>Scheduler settings</h2><p className="muted">The server scheduler runs independently from the extension.</p><div className="switch-row"><div><strong>Auto mode</strong><small>Allow scheduled mock posting</small></div><button className={settings.auto_mode ? 'toggle on' : 'toggle'} onClick={() => onChange({ ...settings, auto_mode: !settings.auto_mode })}><span /></button></div><div className="form-grid"><label>Start time<input type="time" value={settings.start_time} onChange={(event) => onChange({ ...settings, start_time: event.target.value })} /></label><label>End time<input type="time" value={settings.end_time} onChange={(event) => onChange({ ...settings, end_time: event.target.value })} /></label><label>Interval (minutes)<input type="number" value={settings.posting_interval} onChange={(event) => onChange({ ...settings, posting_interval: Number(event.target.value) })} /></label><label>Max posts / day<input type="number" value={settings.maximum_posts_per_day} onChange={(event) => onChange({ ...settings, maximum_posts_per_day: Number(event.target.value) })} /></label></div><label>Minimum messages since last post<input type="number" value={settings.minimum_messages} onChange={(event) => onChange({ ...settings, minimum_messages: Number(event.target.value) })} /></label><label>Working days<div className="day-picker">{days.map((day) => <button className={settings.working_days.includes(day) ? 'day active' : 'day'} key={day} onClick={() => onChange({ ...settings, working_days: settings.working_days.includes(day) ? settings.working_days.filter((item) => item !== day) : [...settings.working_days, day] })}>{day}</button>)}</div></label><button className="button primary" onClick={onSave}>Save scheduler</button></section><section className="panel rules"><p className="kicker">CURRENT RULES</p><h3>Posting guardrails</h3><div className="rule">✓ Only enabled feed groups</div><div className="rule">✓ Groups process in configured order</div><div className="rule">✓ {settings.minimum_messages} messages required</div><div className="rule">✓ Maximum {settings.maximum_posts_per_day} posts per day</div><div className="disclaimer">Stopping the bot prevents new scheduled operations before each feed item is processed.</div></section></div> }

function NotificationsPage({ notifications, onRead, onReadAll }: { notifications: Notification[]; onRead: (id: string) => void; onReadAll: () => void }) { return <section className="panel notification-panel"><div className="panel-head"><div><p className="kicker">INBOX</p><h2>Notifications <span className="count-pill">{notifications.filter((item) => !item.read).length}</span></h2></div><button className="text-button" onClick={onReadAll}>Mark all read</button></div>{notifications.length === 0 ? <div className="empty-state"><span>♢</span><p>No notifications yet.</p></div> : notifications.map((notification) => <button className={notification.read ? 'notification-row read' : 'notification-row'} key={notification.id} onClick={() => onRead(notification.id)}><div className="notification-avatar">{notification.username.slice(0, 1).toUpperCase()}</div><div><strong>@{notification.username}</strong><p>{notification.message}</p><small>{notification.group_name}</small></div>{!notification.read && <span className="unread" />}</button>)}</section> }

function OpportunitiesPage({ opportunities }: { opportunities: Opportunity[] }) { return <section className="panel opportunity-panel"><div className="panel-head"><div><p className="kicker">EVIDENCE-LED DISCOVERY</p><h2>Potential opportunities</h2></div><span className="data-badge">500 messages analyzed</span></div>{opportunities.length === 0 ? <div className="empty-state"><span>↗</span><p>No opportunities analyzed yet.</p><small>Explore opportunities from a group analysis.</small></div> : opportunities.map((opportunity) => <div className="opportunity-row" key={opportunity.id}><span className={`opportunity-icon ${opportunity.category}`}>{opportunity.category === 'investment' ? '$' : '⌁'}</span><div><div className="opportunity-title"><strong>@{opportunity.username}</strong><span className="type-label">{opportunity.category}</span></div><p>“{opportunity.evidence}”</p><small>Evidence: {opportunity.evidence_level} · Confidence: {Math.round(opportunity.confidence * 100)}%</small></div></div>)}<div className="disclaimer">These are AI-assisted signals based on available messages. They are not verified identities or guaranteed intent.</div></section> }

function SettingsPage({ url, onSave, connected }: { url: string; onSave: (url: string) => void; connected: boolean }) { const [value, setValue] = useState(url); return <section className="panel settings-card"><p className="kicker">CONNECTION</p><h2>Backend settings</h2><p className="muted">Point this extension at a local, development, or production FastAPI server.</p><label>API server URL<input value={value} onChange={(event) => setValue(event.target.value)} /></label><div className="connection-line"><span className={connected ? 'status-dot' : 'status-dot offline'} />{connected ? 'Connection healthy' : 'Using local demo data'}<button className="button secondary" onClick={() => { onSave(value); window.location.reload() }}>Test connection</button></div><div className="security-note"><strong>Security boundary</strong><p>AI keys, database credentials, and provider configuration stay on the server. They are never bundled into this extension.</p></div></section> }

export default App
