import { useEffect, useMemo, useState } from 'react'
import { Activity, Bot, ChevronRight, CircleHelp, Clock3, FileText, LayoutDashboard, MessageCircle, Plus, Search, Settings2, ShieldCheck, Sparkles, ToggleLeft, ToggleRight, Users, Zap } from 'lucide-react'
import './styles.css'

type Group = { id: number; name: string; handle: string; members: number; category: string; score: number; status: string; analysis?: string; risk?: string }
type Post = { id: number; title: string; body: string; tone: string; updated_at: string }
type Feed = { id: number; group_id: number; post_id?: number; enabled: boolean; auto_mode: boolean; interval_minutes: number; window_start: string; window_end: string; post_count: number; replies: number }

const API = 'http://localhost:8000/api'
const demoGroups: Group[] = [
  { id: 1, name: 'Remote Builders', handle: '@remote_builders', members: 18420, category: 'Startups', score: 92, status: 'Analysed', analysis: 'Founders exchange launch feedback, hiring leads, and practical growth advice.', risk: 'Avoid unsolicited links and repeated pitches.' },
  { id: 2, name: 'Indie Hackers Europe', handle: '@indiehackers_eu', members: 8320, category: 'SaaS', score: 87, status: 'Ready', analysis: 'Product builders share launches, tooling, and collaboration opportunities.', risk: 'Tie promotional posts to a specific discussion.' },
  { id: 3, name: 'Design & Dev Jobs', handle: '@design_dev_jobs', members: 22100, category: 'Jobs', score: 78, status: 'Ready', analysis: 'A high-volume board for freelance and full-time roles.', risk: 'Follow the group format exactly.' },
]

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`${API}${path}`, init)
  if (!response.ok) throw new Error(`API request failed: ${response.status}`)
  return response.json()
}

export default function App() {
  const [view, setView] = useState('Overview')
  const [groups, setGroups] = useState<Group[]>(demoGroups)
  const [posts, setPosts] = useState<Post[]>([])
  const [feeds, setFeeds] = useState<Feed[]>([])
  const [query, setQuery] = useState('')
  const [selected, setSelected] = useState<Group | null>(demoGroups[0])
  const [running, setRunning] = useState(false)
  const [showPostEditor, setShowPostEditor] = useState(false)
  const [draft, setDraft] = useState({ title: '', body: '', tone: 'Professional' })

  useEffect(() => {
    Promise.all([request<Group[]>('/groups'), request<Post[]>('/posts'), request<Feed[]>('/feeds')]).then(([nextGroups, nextPosts, nextFeeds]) => {
      setGroups(nextGroups); setSelected(nextGroups[0] ?? null); setPosts(nextPosts); setFeeds(nextFeeds)
    }).catch(() => undefined)
  }, [])

  const filteredGroups = useMemo(() => groups.filter(group => `${group.name} ${group.handle} ${group.category}`.toLowerCase().includes(query.toLowerCase())), [groups, query])
  const analyse = async (group: Group) => {
    try { const updated = await request<Group>(`/groups/${group.id}/analyse`, { method: 'POST' }); setGroups(items => items.map(item => item.id === updated.id ? updated : item)); setSelected(updated) } catch { setSelected({ ...group, status: 'Analysed' }) }
  }
  const savePost = async () => {
    if (!draft.title || !draft.body) return
    try { const post = await request<Post>('/posts', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(draft) }); setPosts(items => [post, ...items]); setDraft({ title: '', body: '', tone: 'Professional' }); setShowPostEditor(false) } catch { setPosts(items => [{ ...draft, id: Date.now(), updated_at: new Date().toISOString() }, ...items]); setShowPostEditor(false) }
  }

  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><span className="brand-mark"><Bot size={20} /></span><span>relay<span className="brand-dot">.</span>ops</span></div>
      <div className="workspace-label">WORKSPACE <button title="Workspace settings"><Settings2 size={14} /></button></div>
      <nav>{[['Overview', LayoutDashboard], ['Group research', Users], ['Post library', FileText], ['Posting feeds', Zap], ['Activity log', Activity]].map(([label, Icon]) => <button key={label as string} className={view === label ? 'nav-item active' : 'nav-item'} onClick={() => setView(label as string)}><Icon size={17} />{label as string}{label === 'Activity log' && <span className="nav-count">3</span>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="bridge-state"><span className="status-dot" />Browser bridge offline<div className="bridge-copy">Connect Telegram Web to enable actions.</div><button className="outline-button">Open bridge guide <ChevronRight size={14} /></button></div><div className="user-row"><span className="avatar">JD</span><span><strong>Jordan Davis</strong><small>Local operator</small></span><CircleHelp size={16} /></div></div>
    </aside>
    <main className="main-content">
      <header className="topbar"><div><span className="eyebrow">OPERATIONS CONSOLE</span><h1>{view}</h1></div><div className="top-actions"><span className="api-status"><span className="status-dot green" />API connected</span><button className="icon-button" title="Help"><CircleHelp size={18} /></button><span className="avatar">JD</span></div></header>
      {view === 'Overview' && <><section className="hero-row"><div><p className="lead">A clear view of your browser-operated outreach workspace.</p><div className="hero-actions"><button className="primary-button" onClick={() => setView('Group research')}><Search size={16} />Find groups</button><button className="secondary-button" onClick={() => { setView('Post library'); setShowPostEditor(true) }}><Plus size={16} />Create post</button></div></div><div className="run-control"><div><span className="eyebrow">AUTOMATION</span><strong>{running ? 'Running queue' : 'Queue paused'}</strong><small>{running ? 'Manual stop available' : 'Ready when you are'}</small></div><button className="toggle" onClick={() => setRunning(!running)}>{running ? <ToggleRight size={38} /> : <ToggleLeft size={38} />}</button></div></section><div className="metric-grid"><Metric label="Groups in feed" value={String(feeds.length || 8)} note="2 need review" icon={Users} /><Metric label="Posts this week" value="24" note="+18% vs last week" icon={FileText} /><Metric label="Replies captured" value="61" note="12 unread" icon={MessageCircle} /><Metric label="Queue health" value="92%" note="Within safe limits" icon={ShieldCheck} /></div><section className="content-grid"><div className="panel large-panel"><PanelHeading title="Priority groups" action="View all" onClick={() => setView('Group research')} /><div className="table-head"><span>GROUP</span><span>FIT SCORE</span><span>LAST ACTION</span><span>STATUS</span></div>{groups.slice(0, 3).map(group => <GroupRow key={group.id} group={group} onClick={() => { setSelected(group); setView('Group research') }} />)}</div><div className="panel activity-panel"><PanelHeading title="Recent activity" action="Open log" onClick={() => setView('Activity log')} /><ActivityItem color="teal" title="Reply captured" detail="Remote Builders" time="12 min ago" /><ActivityItem color="orange" title="Post skipped" detail="20-message threshold" time="1 hr ago" /><ActivityItem color="blue" title="Group analysed" detail="Indie Hackers Europe" time="3 hrs ago" /></div></section></>}
      {view === 'Group research' && <Research groups={filteredGroups} query={query} setQuery={setQuery} selected={selected} setSelected={setSelected} analyse={analyse} />}
      {view === 'Post library' && <Library posts={posts} showEditor={showPostEditor} setShowEditor={setShowPostEditor} draft={draft} setDraft={setDraft} savePost={savePost} />}
      {view === 'Posting feeds' && <Feeds groups={groups} feeds={feeds} running={running} setRunning={setRunning} />}
      {view === 'Activity log' && <ActivityLog />}
    </main>
  </div>
}

function Metric({ label, value, note, icon: Icon }: { label: string; value: string; note: string; icon: typeof Users }) { return <div className="metric"><div className="metric-icon"><Icon size={18} /></div><span>{label}</span><strong>{value}</strong><small>{note}</small></div> }
function PanelHeading({ title, action, onClick }: { title: string; action: string; onClick: () => void }) { return <div className="panel-heading"><h2>{title}</h2><button onClick={onClick}>{action}<ChevronRight size={14} /></button></div> }
function GroupRow({ group, onClick }: { group: Group; onClick: () => void }) { return <button className="group-row" onClick={onClick}><span className="group-avatar">{group.name.slice(0, 2).toUpperCase()}</span><span className="group-name"><strong>{group.name}</strong><small>{group.handle} · {group.members.toLocaleString()} members</small></span><strong className="score">{group.score}%</strong><span className="last-action">{group.status === 'Analysed' ? 'Analysed today' : 'Not contacted'}</span><span className={`pill ${group.status.toLowerCase()}`}>{group.status}</span></button> }
function ActivityItem({ color, title, detail, time }: { color: string; title: string; detail: string; time: string }) { return <div className="activity-item"><span className={`activity-marker ${color}`} /><span><strong>{title}</strong><small>{detail}</small></span><time>{time}</time></div> }
function Research({ groups, query, setQuery, selected, setSelected, analyse }: { groups: Group[]; query: string; setQuery: (value: string) => void; selected: Group | null; setSelected: (group: Group) => void; analyse: (group: Group) => void }) { return <section className="research-layout"><div className="panel research-list"><div className="section-title"><div><span className="eyebrow">DISCOVERY</span><h2>Find relevant groups</h2></div><span className="result-count">{groups.length}/50 results</span></div><div className="search-box"><Search size={17} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search topics, industries, or handles" /></div>{groups.map(group => <button className={selected?.id === group.id ? 'research-item selected' : 'research-item'} key={group.id} onClick={() => setSelected(group)}><span className="group-avatar">{group.name.slice(0, 2).toUpperCase()}</span><span><strong>{group.name}</strong><small>{group.handle} · {group.category}</small></span><span className="score">{group.score}%</span></button>)}</div><div className="panel analysis-panel">{selected ? <><div className="analysis-top"><div><span className="eyebrow">GROUP ANALYSIS</span><h2>{selected.name}</h2><p>{selected.handle} · {selected.members.toLocaleString()} members</p></div><button className="secondary-button" onClick={() => analyse(selected)}><Sparkles size={15} />Analyse</button></div><div className="analysis-score"><strong>{selected.score}%</strong><span>partnership fit</span><div className="score-bar"><i style={{ width: `${selected.score}%` }} /></div></div><Insight icon={Users} title="What happens here" text={selected.analysis || 'Analyse this group to understand what members do and how conversations work.'} /><Insight icon={MessageCircle} title="Can I post?" text={selected.analysis ? 'Yes, with a concise, relevant introduction and a clear reason for the collaboration.' : 'Run analysis before selecting a recommended post.'} /><Insight icon={ShieldCheck} title="Account protection" text={selected.risk || 'Keep frequency low, respect group rules, and avoid duplicate messages.'} /><button className="text-action"><Plus size={15} />Add to posting feed</button></> : <div className="empty-state">Select a group to inspect it.</div>}</div></section> }
function Insight({ icon: Icon, title, text }: { icon: typeof Users; title: string; text: string }) { return <div className="insight"><span className="insight-icon"><Icon size={16} /></span><span><strong>{title}</strong><p>{text}</p></span></div> }
function Library({ posts, showEditor, setShowEditor, draft, setDraft, savePost }: { posts: Post[]; showEditor: boolean; setShowEditor: (value: boolean) => void; draft: { title: string; body: string; tone: string }; setDraft: (value: { title: string; body: string; tone: string }) => void; savePost: () => void }) { return <section className="library"><div className="section-title"><div><span className="eyebrow">COPY DESK</span><h2>Your post statements</h2></div><button className="primary-button" onClick={() => setShowEditor(true)}><Plus size={16} />New post</button></div>{showEditor && <div className="panel editor"><input placeholder="Post title" value={draft.title} onChange={event => setDraft({ ...draft, title: event.target.value })} /><textarea placeholder="Write a statement that can be adapted to different groups..." value={draft.body} onChange={event => setDraft({ ...draft, body: event.target.value })} /><div className="editor-footer"><select value={draft.tone} onChange={event => setDraft({ ...draft, tone: event.target.value })}><option>Professional</option><option>Conversational</option><option>Direct</option></select><button className="secondary-button" onClick={() => setShowEditor(false)}>Cancel</button><button className="primary-button" onClick={savePost}>Save post</button></div></div>}{posts.length === 0 && !showEditor ? <div className="panel empty-state"><FileText size={28} /><strong>No saved posts yet</strong><span>Create your first statement to use in a feed.</span></div> : <div className="post-grid">{posts.map(post => <article className="panel post-card" key={post.id}><div className="post-card-top"><span className="pill ready">{post.tone}</span><button className="icon-button"><Settings2 size={16} /></button></div><h3>{post.title}</h3><p>{post.body}</p><small>Updated {new Date(post.updated_at).toLocaleDateString()}</small></article>)}</div>}</section> }
function Feeds({ groups, feeds, running, setRunning }: { groups: Group[]; feeds: Feed[]; running: boolean; setRunning: (value: boolean) => void }) { return <section className="library"><div className="section-title"><div><span className="eyebrow">SEQUENCER</span><h2>Posting feeds</h2></div><button className={running ? 'danger-button' : 'primary-button'} onClick={() => setRunning(!running)}>{running ? 'Stop queue' : 'Start queue'}<Zap size={15} /></button></div><div className="panel feed-settings"><div><h3>Global schedule</h3><p>Manual review remains required for every browser action.</p></div><div className="schedule-fields"><label>Window<input type="time" defaultValue="09:00" /> to <input type="time" defaultValue="20:00" /></label><label>Interval<input type="number" defaultValue="120" /> min</label><label className="switch-label">Auto-mode <input type="checkbox" /></label></div></div><div className="panel feed-table"><div className="table-head"><span>ORDER / GROUP</span><span>POSTS</span><span>LAST RUN</span><span>ACTION</span></div>{(feeds.length ? feeds : groups.slice(0, 3).map((group, index) => ({ id: index, group_id: group.id, enabled: index === 0, auto_mode: false, interval_minutes: 120, post_count: index * 4, replies: index }))).map((feed, index) => <div className="feed-row" key={feed.id}><span><b className="order-number">{index + 1}</b><strong>{groups.find(group => group.id === feed.group_id)?.name || 'Unknown group'}</strong></span><span>{feed.post_count}</span><span>{feed.post_count ? 'Today, 10:40' : 'Never'}</span><button className={feed.enabled ? 'text-action' : 'muted-action'}>{feed.enabled ? 'Enabled' : 'Paused'}</button></div>)}</div></section> }
function ActivityLog() { return <section className="library"><div className="section-title"><div><span className="eyebrow">AUDIT TRAIL</span><h2>Activity log</h2></div><span className="result-count">Last 7 days</span></div><div className="panel log-list"><ActivityItem color="teal" title="Reply captured" detail="Remote Builders · “Sounds interesting, send details”" time="12 min ago" /><ActivityItem color="orange" title="Post skipped" detail="Design & Dev Jobs · 18 messages since last post" time="1 hr ago" /><ActivityItem color="blue" title="Group analysed" detail="Indie Hackers Europe · 500 messages sampled" time="3 hrs ago" /><ActivityItem color="green" title="Queue started" detail="3 feed groups · weekday schedule" time="Yesterday" /></div></section> }